# .ai-project.yaml - shared-ai-configs (dogfooding)
# This project generates AI configs, and uses itself for AI guidance
# Schema: services-based grouping
# Version: 1.1.0

project:
  name: 'shared-ai-configs'
  short_name: 'sac'
  description: 'NPM package for generating AI-assisted development configurations for Claude Code and Cursor IDE'
  role: 'Full-Stack DevTools Engineer'

languages:
  chat: 'Russian'
  code: 'English'

stack:
  framework:
    - 'Commander.js 12'
  language:
    - 'TypeScript 5.3'
  build:
    - 'tsc'
  testing:
    - 'Vitest'
  linting:
    - 'ESLint'

architecture: 'Modular'

architecture_structure: |
  src/cli/
  ├── commands/      # init, generate, validate, status, doctor
  ├── utils/         # config, template, logger
  └── types.ts       # TypeScript interfaces
  core/              # Universal .mdc rules (28 files)
  stacks/            # Stack-specific rules (react/, node/)
  integrations/      # Tool integrations (beads/, github/, gitlab/)
  templates/         # EJS templates for generation
  content/           # Commands, skills, agents, notepads
  hooks/             # Shell/JS hooks for Claude/Cursor
  schema/            # JSON Schema for .ai-project.yaml

services:
  ide:
    primary: 'Cursor'
    secondary: 'Claude Code'
    paths:
      claude: '.claude/'
      cursor: '.cursor/'

  vcs:
    type: 'github'
    main_branch: 'master'

  mcp:
    hindsight:
      enabled: true
    context7:
      enabled: true

# Standard commands (defaults, can be overridden)
commands:
  dev: 'npm run watch'
  build: 'npm run build'
  test: 'npm run test'
  lint: 'npm run lint'
  quality_gates: 'npm run quality'

# Project-specific commands
commands_project:
  lint_fix: 'npm run lint:fix'
  lint_md: 'npm run lint:md'
  format: 'npm run format'
  format_check: 'npm run format:check'
  quality_fix: 'npm run quality:fix'

rules:
  always:
    - 'follow import rule: commands → utils → types (never reverse)'
    - 'use beads for task tracking'
  never:
    - "edit content in dist/ - it's generated"

plugins:
  install:
    - name: 'bd'
      source: 'binary'
      config:
        project_prefix: 'SAC'
        path: '.beads/'

options:
  orchestration: false
  agentic_workflows: false
  sdd_enabled: false

generation:
  targets:
    claude: true
    cursor: false
    beads: true
    claude_md: true
    gitignore_entries: true
  strategy: 'generate'
