import { existsSync, unlinkSync, rmSync } from 'fs';
import { join } from 'path';
import { logger } from '../utils/logger.js';

export interface CleanOptions {
  output: string;
  dryRun?: boolean;
  all?: boolean;
}

/**
 * Directories and files generated by shared-ai-configs.
 *
 * IMPORTANT FILE CLASSIFICATION:
 * - Generated files (.claude/, .cursor/, CLAUDE.md, etc.) = Disposable, regenerated each run
 * - Config files (.ai-project.yaml) = Team settings, version-controlled
 * - Secrets (.env.aiproject) = Personal API keys/tokens, never version-controlled
 */
const GENERATED_DIRS = ['.claude', '.cursor', '.perles'];

const GENERATED_FILES = [
  'CLAUDE.md',
  '.cursorrules',
  '.cursorignore',
  '.cursorindexingignore',
  'AGENTS.md',
];

// Files that should only be removed with --all flag
const OPTIONAL_FILES = ['.env.aiproject'];

export async function cleanCommand(options: CleanOptions): Promise<void> {
  const outputDir = options.output;
  const dryRun = options.dryRun;
  const includeAll = options.all;

  logger.header('Cleaning generated AI configuration files');

  const removed: string[] = [];
  const notFound: string[] = [];

  // Clean directories
  for (const dir of GENERATED_DIRS) {
    const dirPath = join(outputDir, dir);
    if (existsSync(dirPath)) {
      if (!dryRun) {
        rmSync(dirPath, { recursive: true, force: true });
      }
      removed.push(dir + '/');
    } else {
      notFound.push(dir + '/');
    }
  }

  // Clean individual files
  for (const file of GENERATED_FILES) {
    const filePath = join(outputDir, file);
    if (existsSync(filePath)) {
      if (!dryRun) {
        unlinkSync(filePath);
      }
      removed.push(file);
    } else {
      notFound.push(file);
    }
  }

  // Clean optional files only with --all
  if (includeAll) {
    for (const file of OPTIONAL_FILES) {
      const filePath = join(outputDir, file);
      if (existsSync(filePath)) {
        if (!dryRun) {
          unlinkSync(filePath);
        }
        removed.push(file);
      }
    }
  }

  // Report results
  if (removed.length > 0) {
    if (dryRun) {
      logger.info(`Would remove: ${removed.join(', ')}`);
    } else {
      logger.success(`Removed: ${removed.join(', ')}`);
    }
  } else {
    logger.info('No generated files found to clean');
  }

  if (!includeAll && existsSync(join(outputDir, '.env.aiproject'))) {
    logger.info('Note: .env.aiproject preserved (use --all to remove)');
  }

  logger.info('');
  logger.info('To regenerate: npx shared-ai-configs generate');
}
