import { writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { logger } from '../utils/logger.js';
import { getDefaultConfig } from '../utils/config.js';
import type { InitOptions } from '../types.js';

export async function initCommand(options: InitOptions): Promise<void> {
  const configPath = join(process.cwd(), '.ai-project.yaml');

  if (existsSync(configPath) && !options.force) {
    logger.error('.ai-project.yaml already exists. Use --force to overwrite.');
    process.exit(1);
  }

  const stack = options.stack || 'react';
  const projectPath = process.cwd();

  logger.header('Initializing shared-ai-configs');

  const config = getDefaultConfig(projectPath, stack);

  // Generate YAML with new services-based structure
  const configContent = `# AI Project Configuration
# Generated by shared-ai-configs

project:
  name: "${config.project?.name || 'my-project'}"
  short_name: "${config.project?.short_name || 'project'}"
  description: "Project description"
  role: "Senior Developer"

languages:
  chat: "English"   # Language for AI communication (Russian | English)
  code: "English"   # Language for code comments (always English)

stack:
  type: "${stack}"
  framework:
    name: "${config.stack?.framework?.name || 'React'}"
    version: "${config.stack?.framework?.version || '18'}"
  language:
    name: "${config.stack?.language?.name || 'TypeScript'}"
    version: "${config.stack?.language?.version || '5.5'}"
  build:
    tool: "${config.stack?.build?.tool || 'Vite'}"
    version: "${config.stack?.build?.version || '5'}"
  linter: "${config.stack?.linter || 'ESLint'}"

services:
  ide:
    primary: "Cursor"         # Cursor | VSCode | WebStorm | Neovim
    secondary: "none"         # Claude Code | Cursor | VSCode | none
    paths:
      claude: ".claude/"
      cursor: ".cursor/"

  vcs:
    type: "github"            # github | gitlab | bitbucket | none
    main_branch: "main"

  task_tracking:
    type: "none"              # beads | jira | linear | github-issues | none
    # key_prefix: "PROJ-"     # Uncomment if using beads/jira
    # paths:
    #   beads: ".beads/"
    #   perles: ".perles/"

  mcp:
    hindsight:
      enabled: false          # Long-term memory
    snyk:
      enabled: false          # Security scanning
    context7:
      enabled: false          # Library documentation
    memory_bank:
      enabled: false          # Session findings storage
    figma:
      enabled: false          # Design-to-code
    browser:
      enabled: false          # Browser automation

commands:
  dev: "${config.commands?.dev || 'npm run dev'}"
  build: "${config.commands?.build || 'npm run build'}"
  lint: "${config.commands?.lint || 'npm run lint'}"
  test: "${config.commands?.test || 'npm run test'}"
  # codegen: "npm run codegen"
  # quality_gates: "npm run quality:gates"

options:
  dev_server_port: ${config.options?.dev_server_port || 3000}
  # token_optimization: "60-70%"
  # sdd_enabled: true
  # orchestration: false
  # agentic_workflows: false

# rules:
#   critical:
#     - "NEVER edit generated files"
#     - "ALWAYS run quality gates before commit"
#   custom:
#     - "Custom project-specific rule"

# plugins:
#   install:
#     - name: "bd"
#       source: "binary"
#       config:
#         project_prefix: "PROJ-"

architecture:
  structure: |
    src/
    ├── app/       # Entry, providers, router
    ├── pages/     # Route pages
    ├── shared/    # Shared components, utils
    └── index.ts   # Main entry

generation:
  targets:
    claude: true
    cursor: true
    beads: false
    perles: false
    ignore_files: true
    claude_md: true
    gitignore_entries: true
  strategy: "generate"        # generate | symlink | copy
`;

  writeFileSync(configPath, configContent);

  logger.success(`Created .ai-project.yaml`);
  logger.info(`Stack: ${stack}`);
  logger.info('');
  logger.info('Next steps:');
  logger.list([
    'Edit .ai-project.yaml to match your project',
    'Run: npx shared-ai-configs generate',
    'Add generated files to .gitignore',
  ]);
}
