import { writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { logger } from '../utils/logger.js';
import { getDefaultConfig } from '../utils/config.js';
import type { InitOptions } from '../types.js';

export async function initCommand(options: InitOptions): Promise<void> {
  const configPath = join(process.cwd(), '.ai-project.yaml');

  if (existsSync(configPath) && !options.force) {
    logger.error('.ai-project.yaml already exists. Use --force to overwrite.');
    process.exit(1);
  }

  const stack = options.stack || 'react';
  const projectPath = process.cwd();

  logger.header('Initializing shared-ai-configs');

  const config = getDefaultConfig(projectPath, stack);

  // Generate YAML with new array-based structure
  const configContent = `# AI Project Configuration
# Generated by shared-ai-configs

project:
  name: "${config.project?.name || 'My Project'}"
  short_name: "${config.project?.short_name || 'project'}"
  description: "Project description"
  role: "Senior Developer"

languages:
  chat: "English"   # Language for AI communication (Russian | English)
  code: "English"   # Language for code comments (always English)

stack:
  framework:
    - "React 18"
  language:
    - "TypeScript 5.5"
  build:
    - "Vite 5"
  ui:
    - "Ant Design 5"
  state:
    - "TanStack Query 5"
    - "Zustand 5"
  api:
    - "Orval 7"
    - "MSW 2"
  testing:
    - "Vitest"
  linting:
    - "ESLint"

architecture: "FSD"   # FSD | Clean | Layered | Modular

services:
  vcs:
    type: "github"            # github | gitlab | bitbucket | none
    main_branch: "main"

  mcp:
    hindsight:
      enabled: false          # Long-term memory
    snyk:
      enabled: false          # Security scanning
    context7:
      enabled: false          # Library documentation
    memory_bank:
      enabled: false          # Session findings storage
    figma:
      enabled: false          # Design-to-code
    browser:
      enabled: false          # Browser automation

# Standard commands (defaults work for most projects)
commands:
  dev: "npm run dev"
  build: "npm run build"
  lint: "npm run lint"
  test: "npm run test"
  quality_gates: "npm run quality:gates"

# Project-specific commands
commands_project:
  codegen: "npm run codegen"

rules:
  always:
    - "follow FSD structure: app/ → pages/ → widgets/ → shared/"
  never:
    - "edit src/shared/api/generated/ - use npm run codegen instead"

# plugins:
#   install:
#     - name: "bd"
#       source: "binary"
#       config:
#         project_prefix: "PROJ-"
`;

  writeFileSync(configPath, configContent);

  logger.success(`Created .ai-project.yaml`);
  logger.info(`Stack: ${stack}`);
  logger.info('');
  logger.info('Next steps:');
  logger.list([
    'Edit .ai-project.yaml to match your project',
    'Run: npx shared-ai-configs generate',
    'Add generated files to .gitignore',
  ]);
}
